# Site
repository: coddy6
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Aaron Huerta
title: Beginner mobile, desktop and web application developer
email: enginesoftw@gamil.com
email: aaron.huerta9115@alumnos.udg.mx
website: www.github.com/Coddy6

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  Coddy6
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: aaronhs2848
linkedin_username: aaronhuerta9115
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: channel/UCKgOUnCye3pCMSB9gPFML3w
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Credly
  icon: fas fa-certificate
  url: https://www.credly.com/users/aaron-huerta-sigala
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Aaron and I'm a programmer. I have a great desire to contribute my knowledge and skills to the world of work.
  I am passionate about what I study and I want to make known what I have learned, my knowledge and skills in this world of programming and develop my full potential.
  I have experience with desktop applications and some mobile applications, I also use the CMS content manager for web pages.

  I am most skilled in: <mark>C++</mark> and <mark>Flutter</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/Coddy6
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/gentlemani/flutterSchool
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably the first best designed app I have created, using new technologies provided by Google.
        description: | # this will include new lines to allow paragraphs
          This project is done in collaboration with my colleagues, we made a mobile app about food recommendations, it implements AI and algorithms to predict a good meal for the user. It depends on the time zone and providing the meals with nutritional information (you can manage it thanks to the data of a nutritionist).

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Guadalajara
        caption: 2020 - 2024
        sub_title: Computer engineer
        quote: >
          The CUCEI was created in 1994, based on the former faculties of Sciences, Chemical Sciences, Informatics and Computing and Engineering. in addition to the Wood, Pulp and Paper Institutes; Astronomy and Meteorology (IAM) and the Directorate of Linkage and Technology Transfer.
        description: | # this will include new lines to allow paragraphs
          During my studies at CUCEI, I learned many more concepts that I did not know before, I know more about programming, databases, web pages, programming algorithms, improving the performance of my programs, etc. I learned to manage institutional pages with the CMS Drupal... I know how to program with C++ better.

          Every time I learned more and more about the world of technology and artificial intelligence.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Gaming
      - listen to music
      - watch videos

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
